[package]
name = "doku"
version = "0.10.0"
authors = ["Patryk Wychowaniec <patryk.wychowaniec@anixe.pl>"]
license = "MIT"
edition = "2018"
description = "A framework for building documentation"
readme = "../README.md"
repository = "https://github.com/anixe/doku"
keywords = ["doc", "docs", "documentation", "serialization"]

[dependencies]
chrono = { version = "0.4", optional = true }
doku-derive = { version = "=0.10.0", path = "../doku-derive" }
serde = "1.0"

[features]
chrono-04 = ["chrono"]

[dev-dependencies]
difference = "2.0"
doku-test = { path = "../doku-test" }
indoc = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
test-case = "1.2"
