[package]
name = "doku"
version = "0.21.1"
authors = ["Athanasios Katsios <aka@anixe.io>", "Patryk Wychowaniec <patryk.wychowaniec@anixe.pl>"]
license = "MIT"
edition = "2024"
description = "A framework for documenting Rust data structures"
readme = "../README.md"
repository = "https://github.com/anixe/doku"
keywords = ["doc", "docs", "documentation", "serialization"]

[dependencies]
chrono = { version = "0.4", optional = true, default-features = false }
doku-derive = { version = "=0.21.1", path = "../doku-derive" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = { version = "2", optional = true, default-features = false }

[features]
chrono-04 = ["chrono"]
url-2 = ["url"]

[dev-dependencies]
difference = "2.0"
indoc = "2.0"
serde = { version = "1.0", features = ["derive"] }
test-case = { git = "https://github.com/anixe/test-case", branch = "master" }
trybuild = { version = "1.0", features = ["diff"] }
